#!/bin/bash
if [[ -n "$1" ]]
then
  album_hash=${1##*imgur.com/a/}
  if [[ -n "$2" ]]
  then
    if [[ "$2" == "-1" ]]
    then
      client_id=ffffffffffffffff # your id here
    else
      client_id=$2
    fi
    url_list=$(curl -s https://api.imgur.com/3/album/${album_hash}/images -H "Authorization: Client-Id ${client_id}" |
    python -c "import sys, json; print reduce(lambda a,b:a + '\n'+b, [image['link'].encode('ascii') for image in json.load(sys.stdin)['data']]);")
  else
    url_list=$(curl -s -H "Host: api.imgur.com" "https://api.imgur.com/post/v1/posts/${album_hash}?client_id=546c25a59c58ad7&include=media" |
      python -c 'import sys,json; jsondata = json.load(sys.stdin); numimages = jsondata["image_count"]; print(reduce(lambda a,b:a+"\n"+b, [media["url"] for media in jsondata["media"]]))')
  fi
  for url in $url_list
  do
    echo Downloading $url
    curl -sLO $url
  done
else
  echo no album hash provided
fi
